[options]
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  enable_guicolors = true
  guifont = "JetBrains Mono Regular:h11"

  buffer_index_type = 4

  # Vim
  escape_key_binding = 'jj'

  # Plugins
  enable_statusline_mode = true
  statusline_separator = 'nil'
  statusline_iseparator = 'nil'

  autocomlete_method = 'coc'
  enable_tabline_filetype_icon = true
  filetree_direction = 'left'

  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '!node_packages/']
  bootstrap_before = 'myspacevim#before'

[[layers]]
  name = 'git'

# [[layers]]
#   name = 'VersionControl'

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = 'complete'
  auto_completion_tab_key_behavior = 'smart'

[[layers]]
  name = "checkers"
  lint_on_the_fly = true
  auto_completion_return_key_behavior = 'nil'
  auto_completion_tab_key_behavior = 'smart'

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

[[layers]]
  name = 'colorscheme'

[[layers]]
  name = 'denite'

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#python"
