[git]
    autoCommit = true
    autoPush = true

[data]
     

[data.home]
    username = "edvein-rin"
    email = "edvein-rin@gmail.com"

[data.work]
    username = "e.tsakhlo"
    email = "e.tsakhlo@smartweb.com.ua"

[data.github]
    

